# Generated by Django 3.1.4 on 2020-12-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201211_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
    ]
